In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
data_1d = np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
data_2d = np.array([[1,2,3],[4,5,6]])

In [8]:
print(data_2d.shape)

(2, 3)


In [18]:
reshaped_data = data_2d.reshape(2,3)
print(reshaped_data)
print(reshaped_data.shape)
print(reshaped_data.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [16]:
print(data_1d.ndim)
print(reshaped_data)
print(reshaped_data.ndim)


1
[[1 2]
 [3 4]
 [5 6]]
2


In [15]:
print(data_2d[0])

[1 2 3]


In [21]:
print(data_2d[1,2])

6


In [33]:
print(data_2d[:1])

[[1 2 3]]


In [34]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c = a+b
print(c)

[5 7 9]


In [36]:
print(a*b*c)

[ 20  70 162]


In [37]:
exp_a = np.exp(a)
print(exp_a)

[ 2.71828183  7.3890561  20.08553692]


In [38]:
a= np.array([1,2,3])
b = 10
result = a+b
result

array([11, 12, 13])